'use client';
import {ArrowLeft,ArrowUpRight,BookOpen,Check,Download,ExternalLink,Headphones,LoaderCircle,Pause,Play,SkipBack,SkipForward,Square} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {ArtImage} from './art-image';
import type {Guide} from '@/lib/types';
import type {LocalGuide} from '@/lib/local';
import type {useSpeech} from '@/hooks/use-speech';
export type Speech=ReturnType<typeof useSpeech>;
export function GuideDetail({guide,row,speech,busy,online,onBack,onDownload,onRemove,onSettings}:{guide:Guide;row?:LocalGuide;speech:Speech;busy:boolean;online:boolean;onBack:()=>void;onDownload:()=>void;onRemove:()=>void;onSettings:()=>void}){
 const natural=speech.engine==='natural';
 const preparing=speech.state.status==='preparing'||speech.state.status==='generating';
 const description=natural
  ? speech.modelState.status==='ready'?'Kokoro 中文自然声已在本机就绪。':speech.modelState.cached?'本地自然声已下载，首次播放时加载。':'首次使用需下载约 170 MB，之后可以离线朗读。'
  : speech.voice?'使用 Windows 中文系统声音，即时朗读。':'尚未找到 Windows 中文系统声音。';
 const action=preparing?(speech.state.status==='preparing'?`准备自然声 ${speech.modelState.progress||''}${speech.modelState.progress?'%':''}`:'正在生成当前句…'):speech.state.status==='speaking'?'暂停':speech.state.status==='paused'?'继续讲解':'开始讲解';
 return <div className="detail"><div className="detail-actions"><Button variant="ghost" onClick={onBack}><ArrowLeft/>返回</Button>{row?.offline?<Button variant="outline" onClick={onRemove}><Check/>已保存离线 · 移除</Button>:<Button variant="outline" onClick={onDownload} disabled={busy||!online}>{busy?<LoaderCircle className="spin"/>:<Download/>}保存离线</Button>}</div><div className="detail-heading"><div><span className="eyebrow gold">{guide.type} · {guide.country} · {guide.year}</span><h1>{guide.title}</h1><p className="original">{guide.originalTitle}</p></div><div className="guide-meta"><span>{guide.creator}</span><span>{{zh:'中文',ja:'日本語',en:'English'}[guide.language]} · 约 {guide.duration} 分钟</span>{guide.demo&&<span>编辑示例 · 本机履历</span>}</div></div><ArtImage guide={guide} row={row} className="detail-image"/><p className="image-credit">{guide.imageCredit}{guide.imageSource&&<a href={guide.imageSource} target="_blank" rel="noreferrer"> 图片来源 <ExternalLink size={12}/></a>}</p><div className="reading-grid"><Tabs defaultValue="reading" className="reading"><TabsList variant="line"><TabsTrigger value="reading"><BookOpen/>作品介绍</TabsTrigger>{guide.language==='zh'&&<TabsTrigger value="speech"><Headphones/>口播文本</TabsTrigger>}<TabsTrigger value="sources">参考来源</TabsTrigger></TabsList><TabsContent value="reading"><article lang={guide.language==='zh'?'zh-CN':guide.language}>{guide.sections.map((s,i)=><section className="prose-section" key={i}><h3>{s.title}</h3><p>{s.text}</p></section>)}</article></TabsContent>{guide.language==='zh'&&<TabsContent value="speech"><div className="transcript">{speech.sentences.map((s,i)=><p key={i} className={speech.state.index===i&&speech.state.status!=='idle'?'current-sentence':''}><span>{String(i+1).padStart(2,'0')}</span>{s}</p>)}</div></TabsContent>}<TabsContent value="sources"><div className="sources">{guide.sources.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span><div>{s.title}<small>{new URL(s.url).hostname}</small></div><ExternalLink size={16}/></a>)}<p className="quiet">史实与解读可能随研究更新。来源链接需要联网打开。</p></div></TabsContent></Tabs><aside className="listen-card"><Headphones className="gold" size={25}/><h3>听一段作品的故事</h3>{guide.language==='zh'?<><p>{description}</p><Button onClick={()=>speech.state.status==='speaking'?speech.pause():speech.resume()} disabled={!speech.canPlay||preparing}>{preparing?<LoaderCircle className="spin"/>:speech.state.status==='speaking'?<Pause/>:<Play/>}{action}</Button><button className="text-link" onClick={onSettings}>选择朗读声音 <ArrowUpRight size={14}/></button><p className="small-note">{natural?'免费 · 本机生成 · 不保存音频':'免费 · 系统声音 · 不保存音频'}</p></>:<p>本版只提供中文语音。你仍可阅读和离线保存这篇介绍。</p>}</aside></div></div>;
}
export function Player({guide,speech}:{guide:Guide;speech:Speech}){
 const preparing=speech.state.status==='preparing'||speech.state.status==='generating';
 const active=['preparing','generating','speaking','paused'].includes(speech.state.status);
 const label=speech.state.status==='preparing'?`准备自然声 ${speech.modelState.progress||''}${speech.modelState.progress?'%':''}`:speech.state.status==='generating'?'正在生成当前句':speech.state.status==='paused'?'已暂停':speech.state.status==='speaking'?'正在讲解':speech.state.status==='ended'?'讲解结束':speech.engine==='natural'?'Kokoro 本地自然声':'Windows 系统声音';
 const caption=speech.state.error||(!speech.canPlay?'当前浏览器无法使用所选声音':speech.state.status==='idle'?'上一句 / 下一句 · 不保存音频':speech.sentences[speech.state.index]);
 return <div className="player" aria-label="中文讲解控制"><div className="player-title"><Headphones/><div><strong>{guide.title}</strong><span>{label} · 第 {speech.state.index+1} / {speech.sentences.length} 句</span></div></div><div className="player-controls"><Button variant="ghost" size="icon" aria-label="上一句" title="上一句" disabled={!active||speech.state.index===0} onClick={()=>speech.move(-1)}><SkipBack/></Button><Button className="play-button" size="icon" aria-label={speech.state.status==='speaking'?'暂停':'播放或继续'} disabled={!speech.canPlay||preparing} onClick={()=>speech.state.status==='speaking'?speech.pause():speech.resume()}>{preparing?<LoaderCircle className="spin"/>:speech.state.status==='speaking'?<Pause/>:<Play/>}</Button><Button variant="ghost" size="icon" aria-label="下一句" title="下一句" disabled={!active||speech.state.index===speech.sentences.length-1} onClick={()=>speech.move(1)}><SkipForward/></Button><Button variant="ghost" size="icon" aria-label="停止" title="停止" onClick={speech.stop}><Square size={17}/></Button></div><div className="player-caption" role="status">{caption}</div></div>;
}
